### ISSUE TITLE
Why do we have clickable text in API docs?

### ISSUE THREAD

**Issue by yasassri** [ballerina-lang/website#191]
![screenshot from 2017-10-11 11-59-22](https://user-images.githubusercontent.com/7681361/31425197-cd639404-ae7b-11e7-982b-31f7fdc0a80c.png)

**Comment by pubudu91** [comment]
For non-primitive types, it should link to the place where those types are defined. For example, in the screenshot you have provided, clicking on Session should take you to the place in the API docs where Session struct is documented. This is fixed in the Docerina 0.94, though it still adds hyperlinks to primitive types as well.
